version: '3'
services:
  web:
    build:
      context: .
      dockerfile: node.dockerfile
    command: npm run nodemon
    volumes:
      - .:/app
    ports:
      - "3000:3000"

  webpack:
    build:
      context: .
      dockerfile: node.dockerfile
    command: npm run watch

  ganache:
    image: trufflesuite/ganache-cli
    command: ganache-cli -m "Jojoca doesn't fail" -e 0
    ports:
      - 8545:8545
