version: '3'
services:
  web:
    build:
      context: .
      dockerfile: python.dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000  
    ports: 
      - 8000:8000
    volumes:
      - .:/project
  node:
    build:
      context: .
      dockerfile: node.dockerfile
    command: npm run watch
    volumes:
      - .:/app
    
  ganache:
    image: trufflesuite/ganache-cli
    command: ganache-cli -m "Jojoca doesn't fail" -e 0
    ports:
      - 8545:8545
    